In [3]:
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np

In [4]:
df=pd.read_csv('simple_ols_2_columns.csv')

In [5]:
df.head()

   Size_sqft  Price_lakhs
0        800           40
1        900           45
2       1000           55
3       1100           65
4       1200           75

In [39]:
class LR_OLS:
    def __init__(self):
        self.m = None
        self.b = None

    def fit(self,x_train,y_train):
        num = 0
        den = 0
        for i in range(x_train.shape[0]):
            num = num + ((x_train.iloc[i] - x_train.mean())*(y_train.iloc[i] - y_train.mean()))
            den = den + ((x_train.iloc[i] - x_train.mean())*(x_train.iloc[i] - x_train.mean()))
        self.m = num/den
        self.b = y_train.mean() - (self.m * x_train.mean())
        print(self.m)
        print(self.b)

    def predict(self,x_test):
        print(x_test)
        return self.m * x_test + self.b

In [40]:
import numpy as np

In [41]:
import pandas as pd

In [42]:
df=pd.read_csv('OLS CODE.csv')

In [43]:
df.head()

   Size_sqft  Price_lakhs
0        800           40
1        900           45
2       1000           55
3       1100           65
4       1200           75

In [44]:
x=df.iloc[:,0]
y=df.iloc[:,1]

In [45]:
x

0      800
1      900
2     1000
3     1100
4     1200
5     1300
6     1400
7     1500
8     1600
9     1700
10    1800
11    1900
12    2000
13    2100
14    2200
Name: Size_sqft, dtype: int64

In [46]:
y

0      40
1      45
2      55
3      65
4      75
5      85
6      95
7     110
8     120
9     135
10    150
11    165
12    180
13    200
14    220
Name: Price_lakhs, dtype: int64

In [47]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2,random_state=2)

In [48]:
x_train.shape

(12,)

In [49]:
lr=LR_OLS()

In [50]:
lr.fit(x_train,y_train)

0.12681833277980736
-73.3676519428761

In [51]:
x_train.shape[0]

12

In [52]:
x_train[0]

np.int64(800)

In [54]:
x_train.mean()

np.float64(1508.3333333333333)

In [56]:
x_test.iloc[0]

np.int64(1900)

In [60]:
print(lr.predict(x_test.iloc[0]))

1900
167.5871803387579